### ISSUE TITLE
No support for more information requests when creating merchants

### ISSUE THREAD

**Issue by mjallday** [balanced/balanced-ruby#12]
The balanced API [returns a 300 response](https://www.balancedpayments.com/docs/api#requests-for-more-information) when it fails to identify a merchant.

The ruby client does not support this and should raise an exception along with an appropriate message and a URL that the marketplace can redirect the user to to collect more information.

**Comment by mahmoudimus** [comment]
This is fixed as of version 0.3.4. Referencing commit: https://github.com/balanced/balanced-ruby/commit/d2a2e2c876ae595e2eecfcd4bab26d5a991832be
