### ISSUE TITLE
When testing in rspec, you can't expect an exception to be raised without any arguments, which seems to go against standard rspec testing practices

### ISSUE THREAD

**Issue by jondkinney** [balanced/balanced-ruby#134]
Take the following controller spec example. 

``` ruby
require 'spec_helper'

describe BankAccountsController do
  let(:bank_account) { double('BankAccount') }
  let(:owner) { double('Owner').as_null_object }
  let(:balanced_customer_service) { double('BalancedCustomerService') }
  let(:balanced_bank_account) { double('BalancedBankAccount') }
  let(:logger) { Rails.logger }

  context 'existing bank account' do
    before do
      user = FactoryGirl.create(:investor_user)
      @bank_account_db =
        FactoryGirl.create(:bank_account, balanced_uri: 'asdf', owner: user)
    end

    describe 'verifying' do
      context 'ask for verification amounts' do
        it 'renders the verify form' do
          get :verify, id: @bank_account_db.id
          expect(assigns(:bank_account)).to eq(@bank_account_db)
        end
      end

      context 'submits the verification to the balanced API' do
        before do
          allow(Balanced::BankAccount).
            to receive(:find).
            and_return(balanced_bank_account)

          @verification = double('Verification')

          balanced_bank_account.
            stub_chain(:verifications, :find, :first).
            and_return(@verification)

          allow(@verification).to receive(:amount_1=)
          allow(@verification).to receive(:amount_2=)
        end

        context 'saving the verification returns an error' do
          context 'Balanced::BankAccountVerificationFailure' do
            before do
              allow(@verification).
                to receive(:save).
                and_raise(Balanced::BankAccountVerificationFailure, {})
            end

            context 'at least one attempt left' do
              before do
                allow(@verification).to receive(:remaining_attempts).and_return(2)
              end

              it 'tells the user how many attempts they have left' do
                post :submit_verification, id: @bank_account_db.id,
                  verification_1: '1', verification_2: '2'

                expect(flash[:error]).to include('You have 2 attempts remaining')
              end
```

You can see and_raise(Balanced::BankAccountVerificationFailure, {}) requires a second argument, an empty hash (a string won't do).

If I omit the empty hash I receive the following error:

```
1) BankAccountsController existing bank account verifying submits the verification to the balanced API saving the verification returns an error Balanced::BankAccountVerificationFailure at least one attempt left tells the user how many attempts they have left
  Failure/Error: allow(@verification).to receive(:save).and_raise(Balanced::BankAccountVerificationFailure)
  ArgumentError:
    wrong number of arguments (0 for 1)
  # (eval):7:in `to'
  # ./spec/controllers/bank_accounts_controller_spec.rb:147:in `block (7 levels) in <top (required)>'
```

I spoke with some folks in the rspec room on IRC and while the specifics are a bit above my head, they mentioned that it seems your custom Exception class is implemented incorrectly. 

I'd love to help fix this, I'm just not entirely sure where to start.

**Comment by steveklabnik** [comment]
Yeah, seems like https://github.com/balanced/balanced-ruby/blob/master/lib/balanced/error.rb#L8 and https://github.com/balanced/balanced-ruby/blob/master/lib/balanced/error.rb#L55 needs a deafult.

**Comment by mjallday** [comment]
I think it's legitimate to require these exceptions to take an argument since they expect to be able to populate certain properties on themselves from this information.

You _could_ make the base [error constructor](https://github.com/balanced/balanced-ruby/blob/master/lib/balanced/error.rb#L8) take a null argument but then accessing any properties on the error is going have unexpected consequences. e.g. [Error.error_message](https://github.com/balanced/balanced-ruby/blob/master/lib/balanced/error.rb#L23) is going to not like having a null response body.

If I were writing your tests @jondkinney, I would instantiate the error class with an actual response that the API generates so I can closely simulate how everything works in the real world. 

In this particular case the response would look like

``` json
{
  "status": "Conflict",
  "category_code": "bank-account-authentication-not-pending",
  "additional": null,
  "status_code": 409,
  "description": "Some error message here. Your request id is OHM6f24465c76eb11e3aa2a026ba7cac9da.",
  "category_type": "logical",
  "_uris": {},
  "request_id": "OHM6f24465c76eb11e3aa2a026ba7cac9da",
  "extras": {}
}
```

I'm going to close this issue, however I think both of you have more experience in the ruby/rails world than I do, if the expectation in ruby is that you should be able to create an instance of an error without any arguments then please reopen and we can fix that issue.

**Comment by jondkinney** [comment]
@mjallday I hear what you're saying there with wanting to require more specificity, but it seems to me that additional specificity should be optional in this case. Perhaps you'd want to test that the exception raised had a certain 'state' or 'category_code' in a given context, but a lot of times the fact that the exception was raised at all is enough for a test.

If nothing else, I think modifying the code as @steveklabnik suggested above would be more in line with what folks have come to expect when testing with rspec. I don't know if maintaining 'standard practice compatibility' with a popular test framework is a good enough reason to alter your code... but that's exactly what one of the maintainers of rspec who I spoke with via IRC suggested I reach out and present to you as a suggestion. The fact that I couldn't do this tripped me up for several hours when initially specing out our balanced integration.

**Comment by steveklabnik** [comment]
I can see both sides of this.

@myronmarston what do you think about this?

**Comment by myronmarston** [comment]
RSpec does support `and_raise(exception_instance)`, so users can always instantiate the exception class themselves with whatever arguments are needed.

Whether or not you define your exception classes to be instantiatable with no arguments is up to you.  I think it comes down to how much you optimize your library for testability. Making exception classes instantiatable with no arguments makes it easier to write tests involving those classes.  On the other hand, it also makes it easier to use `raise ExceptionClass` (with no args) in production code which could be a problem if that shouldn't be allowed.

I personally tend to favor testability above almost everything else, but that reflects my personal strengths and preferences.  Library maintainers can reasonably choose the other path.

**Comment by steveklabnik** [comment]
:heart: 

Well, since it won't be useful _other_ than for testing, I think erring on the side of what we already have makes sense. If someone can present a strong argument for changing it, I'm totally open to, but seems to me like it's good for now.
