### ISSUE TITLE
Segmentation fault after calling a Balanced::Customer's active_card from controller

### ISSUE THREAD

**Issue by adambarthelson** [balanced/balanced-ruby#139]
```
/balanced-0.7.4/lib/balanced/resources/resource.rb:212: [BUG] Segmentation fault
```

Running this from the rails console works fine, but from a web server (I've tried Webrick, Thin, Unicorn) it hangs after active card is returned in render.

Ruby versions 1.9.3. p327 falcon patched as well as 1.9.3 p 484

balanced-0.7.4/lib/balanced/resources/resource.rb#contruct_from_response, payload being a successful response, returning the instance, in the action controller's (actionpack/lib/action_controller/metal/implicit_render.rb) send_action, it breaks.

```
  def cleanup_view_runtime
    22:   if ActiveRecord::Base.connected?
    23:     db_rt_before_render = ActiveRecord::LogSubscriber.reset_runtime
 => 24:     runtime = super
    25:     db_rt_after_render = ActiveRecord::LogSubscriber.reset_runtime
    26:     self.db_runtime = db_rt_before_render + db_rt_after_render
    27:     runtime - db_rt_after_render
    28:   else
    29:     super
    30:   end
    31: end
```

**Comment by adambarthelson** [comment]
Was using Faraday 0.8.9, locking faraday at 0.8.8 didn't fix.

**Comment by steveklabnik** [comment]
Because we don't have any C code, it shouldn't be possible for us to segfault. That said, in theory, we could do something to trigger a bug in a dependency, maybe, but the bug would be there, not here.

Does this happen without the falcon patches?

Also, random note: you've only got about a year left for 1.9.3, you should upgrade: https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/

**Comment by adambarthelson** [comment]
I noticed the update about 1.9.3 while reinstalling ruby a couple times trying to fix this lol.

While bisecting commits I found that the problem may have come after someone else had explicitly added the 'faraday_middleware' gem.  Still trying to figure it out.

**Comment by adambarthelson** [comment]
This happens with and without falcon patches.

**Comment by adambarthelson** [comment]
Found the issue, not Balanced related.  A segmentation fault was caused by cleanup_view_runtime exploding when an array became too large.  

Surprise!  300 million elements. oops

**Comment by mjallday** [comment]
Thanks for letting us know the resolution @adambarthelson
