### ISSUE TITLE
Find all credits with status failed

### ISSUE THREAD

**Issue by sithara** [balanced/balanced-ruby#153]
Is there a way to find records or reports with status failed.

I have seen the find method..but can I add extra conditions to it ?

**Comment by mjallday** [comment]
Thanks for bringing this up @sithara, we have an open ticket to add examples of how to query and filter in the docs balanced/balanced-docs#8

The syntax you're looking for is `Balanced::Debit.all(:status => 'failed')` where failed can be any state on a transaction.

Let us know if you have any issues.

**Comment by sithara** [comment]
Just curious what if the admin make un-wanted debits from a customers
account.there could be chances of misuse ..is there a debit blocking
condition or something of that sort ?

**Comment by mjallday** [comment]
Sorry, I don't understand the question. If you're a marketplace owner you can do anything with the customer's card but you're also on the hook for any dispute charges that result from misuse.

**Comment by sithara** [comment]
Okies I got my answer .sorry but I have one more doubt
I'm creating an app .What I'm doing is wen a customer enters his persnl
information in my site..I'm creating a customer ,creating an account using
his bank information n linking the account to that customer profile in
balanced to credit his account.im saving the bank account token for future
reference of that account. http://account.is/

Is this workflow correct ?

**Comment by mjallday** [comment]
yes.

**Comment by taylorbrooks** [comment]
@mjallday I'm trying to find failed debits originating from a Bank Account. I'm using a similar query to yours above, then iterating over the debits. Like so:

``` ruby
failed_debits = Balanced::Debit.where(status: 'failed')
failed_debits.each do |d| 
  if d.source._type == 'bank_account'
    p "#{d.created_at} #{d.amount} #{d.customer.name} #{d.appears_on_statement_as}"
  end
end
```

The problem here is that the debit `source` class is sometimes:

``` ruby
Balanced::Card
Balanced::BankAccount
Hash
```

Why would it return a hash? Using 0.7.4

**Comment by sithara** [comment]
hi marshall

now all of a sudden I'm getting an error when I try to access
Balanced::Customer

Its giving me unintialized constant.

**Comment by mjallday** [comment]
@sithara @taylorbrooks can you please open new issues for both these questions?
