### ISSUE TITLE
Implement/Follow Semantic Versioning

### ISSUE THREAD

**Issue by nealtovsen** [balanced/balanced-ruby#155]
Ruby Gems should follow Semantic Versioning, per http://semver.org/

The latest version (0.7.5) implements a breaking change by refactoring #destroy to #unstore (0.7.2), which does not meet Semantic Versioning guidelines. This causes considerable pain for users of the gem.

**Comment by mjallday** [comment]
+1 for the general concept. 

It looks to me like [`unstore`](https://github.com/balanced/balanced-ruby/blame/rev0/lib/balanced/resources/resource.rb#L70) was an additive change tho, it didn't remove any existing functionality.

What's breaking for you?

**Comment by nealtovsen** [comment]
OK. I'm going to close this as it looks like it was some sort of mistake my part.

The actual mistake was getting myself lost in the commits/versions here while trying to figure out what was going on in our software. I must've looked at something backward and jumped to a bad conclusion.

But, FWIW, the source of it all started with some bundler behavior I still can't quite figure out. It looks like we we had been on 0.7.4 for some time (using unstore in our code). I did a bundle update on balanced recently and it somehow resulted in us getting sent backward to 0.7.2 (which didn't have unstore). This resulted in a bug in our software...and confusion ensues.

There was no change in our gemfile so I'm not sure how/why it happened. In any case, I've now done another bundle update, landed on 0.7.5, and everything seems fine...
