### ISSUE TITLE
Improve offset functionality

### ISSUE THREAD

**Issue by sgrshah** [balanced/balanced-ruby#160]
Every month we pull all of our balanced debits and refunds, which I'm sure many companies do. To cycle through all of our transactions we provide a limit of 25 and increase the offset by 25 each time. However, if we sell more products while pulling the transactions, the offset seems to change. So, instead of pulling the 1000-1025 it pulls 999-1024 creating duplicates in our data set. Would be great to set the offset point when first starting to pull.

**Comment by mjallday** [comment]
You're right that some sort of frozen pagination would be a good solution. 

In the meantime you can specify a sort order for the Balanced ruby client and that will work just as well for your use-case:

``` ruby
Balanced::Credit.all(:sort => 'created_at,asc')
```

will return all credits sorted by `created_at` ascending.
