### ISSUE TITLE
Tokenizing a card directly without passing an address will return state=> 'CA' 

### ISSUE THREAD

**Issue by rserna2010** [balanced/balanced-ruby#167]
card = Balanced::Card.new(
  :cvv => '123',
  :expiration_month => '12',
  :expiration_year => '2020',
  :number => '5105105105105100',
  :address => {
    :city=> "BROOKLYN",
    :line1=> "219 17TH STREET",
    :postal_code=> "11215",
    :country_code=> "USA"
  }
).save

https://dashboard.balancedpayments.com/#/marketplaces/TEST-MPJ1TvJrxnGlUGPG0Fpa0ey/logs/OHM6c91eddeb6bc11e3a2f602a1fe53e539

**Comment by rserna2010** [comment]
Actually it's not exclusive to ruby, happens in Balanced.js as well. Guessing it's an api issue. Closing the issue.

**Comment by blim8183** [comment]
Is there a story in the api project that I can follow?

**Comment by mjallday** [comment]
@blim8183 balanced/balanced-api#552
