### ISSUE TITLE
Unstoring sometimes takes a long time

### ISSUE THREAD

**Issue by dmastylo** [balanced/balanced-ruby#168]
On Heroku with production keys unstoring a customer without a credit card associated can sometimes take a long time, ie >10 seconds, to get a response. Not sure if this is an isolated hiccup or if this is common.

**Comment by remear** [comment]
Response times often depend on API load. This isn't a client issue so I'm closing this. If unstore response times start taking longer than this, feel free to open an issue at https://github.com/balanced/balanced-api/issues.
