### ISSUE TITLE
Faraday error

### ISSUE THREAD

**Issue by EMRJ** [balanced/balanced-ruby#173]
Couldn't start getting following error
`method_missing': undefined method`register_middleware' for # Faraday::Connection:0x00000002513f18> (NoMethodError)

gems I installed
**\* LOCAL GEMS ***
faraday (0.9.0)
faraday_middleware (0.9.1)

**Comment by mjallday** [comment]
The balanced gem has a [dependency on faraday 0.8.6](https://github.com/balanced/balanced-ruby/blob/master/balanced.gemspec#L13) so I suspect that's the issue here. 

We can look at what's involved with upgrading, personally I'm not sure what the differences are between those versions but it sounds like it's not a drop-in replacement.

**Comment by mjallday** [comment]
Noting that #172 will let us relax this dependency.

**Comment by remear** [comment]
@EMRJ Would you create a gist (https://gist.github.com) of the output of `bundle list` and link it here. Also, was this on any particular API call?

**Comment by remear** [comment]
balanced-ruby is not yet compatible with faraday 0.9.0. We'll work on fixing this. For now you should use faraday 0.8.6.

**Comment by remear** [comment]
Appears to be a bug in faraday when used with VCR. https://github.com/vcr/vcr/issues/386

**Comment by thepixelmonk** [comment]
why is this issue closed, I'm still getting the above error

**Comment by mjallday** [comment]
@saiko-chriskun you'll get more help if you provide us a reproducible example so we can try and resolve you issue.

questions like 
- what's your environment like? 
- which version of the gem do you have installed? 

will also aid us in resolving your problem.

**Comment by lizixroy** [comment]
Hi there, what's the progress on this issue?

I have got stuck with this. 

"NoMethodError: undefined method `register_middleware' for #Faraday::Connection:0x007f949b46e538" is the error I got when I run rake db:migrate.

I have Faraday 0.9.0 and 0.9.1 installed on my system.

**Comment by mjallday** [comment]
Hey @lizixroy. Given Balanced will cease processing within the next few weeks there's no chance this will be resolved.
