### ISSUE TITLE
Duplicate Customers

### ISSUE THREAD

**Issue by fedesoria** [balanced/balanced-ruby#187]
When calling `Balanced::Customer.new(customer_data)` it should return a response that the Customer already exists with the `customer_uri` so we don't end up with duplicates of customers.

**Comment by remear** [comment]
This isn't a balanced-ruby issue. If you'd like to propose this as an API feature, you're welcome to open an issue at https://github.com/balanced/balanced-api/issues

**Comment by fedesoria** [comment]
Thanks.
