### ISSUE TITLE
Add support for Invoices

### ISSUE THREAD

**Issue by taylorbrooks** [balanced/balanced-ruby#199]
Looks like this works: `curl https://api.balancedpayments.com/invoices -H "Accept: application/vnd.api+json;revision=1.1" -u ak-test-GHsDIaWXkvZIo89IMWPrYTxfhAXTWVI0:`

**Comment by remear** [comment]
The Invoice resource is not officially spec'd and documented and is therefore subject to change. Once it's defined in an API spec and documented we'll definitely add support for it here.

I'd appreciate your comments on https://github.com/balanced/balanced-api/issues/307 to voice your desire for this feature.
