### ISSUE TITLE
Unable to fetch previously created Customer

### ISSUE THREAD

**Issue by adnankhantech** [balanced/balanced-ruby#206]
I have created customer resource and save the customer href inside my database.I'm trying to find the existing customers as:

``` ruby
Balanced::Customer.fetch(self.balanced_uri)
```

where self.balanced_uri is the customer.href
But it gives me this error:

``` ruby
Balanced::Forbidden: Balanced::Forbidden(403)::Forbidden:: GET https://api.balancedpayments.com/customers/CU4dGEmvVcmbqikQhhZvohc4: not-authorized: You cannot access customer CU4dGEmvVcmbqikQhhZvohc4 Your request id is OHM5e1c8b109fe611e4940e0230f00c9248. 
```

**Comment by mjallday** [comment]
@adnan87 you're using the API key associated with "TEST-MP1bo5fDFQ2z4mjksd8ki64E" to fetch the customer, it was created under marketplace "TEST-MP13ZcrWilidn4G0O0cZ0GhL"

**Comment by adnankhantech** [comment]
@mjallday thanks a lot for your input, it worked!!!.
The issue was the customer.href which I was using was of the a different env stored previously inside my database.
Thanks again :+1:
