### ISSUE TITLE
appears_on_statement_as is not supported when creating a credit via a bank account

### ISSUE THREAD

**Issue by mjallday** [balanced/balanced-ruby#38]
https://github.com/balanced/balanced-ruby/blob/master/lib/balanced/resources/bank_account.rb#L37

It is not parsed out of the options dict.

A work around exists:

```
credit = Balanced::Credit.new(
    :amount => amount_in_cents, 
    :appears_on_statement_as => 'MIKES TACOS', 
    :account_uri => merchant.uri
).save
```

**Comment by zealoushacker** [comment]
Also there's duplication in https://github.com/balanced/balanced-ruby/blob/master/lib/balanced/resources/account.rb#L83

**Comment by ajsharp** [comment]
+1. Need this.

**Comment by zealoushacker** [comment]
So I dug deeper...

I now understand what's going on and would like to make some constructive suggestions.

Your one and only interface should always be one of the resource objects. You should not be re-defining your interface via consumers of this interface. Indeed, the only things that need to be in the specific interface implementations are the differences (DRY). So in this example, your one and only interface should be the `Credit` object. It should define its required parameters and throw errors when those requirements aren't met. 

It does not make sense to duplicate this code every time you need to create a `Credit`:

``` ruby
      options = args.last.is_a?(Hash) ? args.pop : {}
      amount = args[0] || options.fetch(:amount) { nil }
      description = args[1] || options.fetch(:description) { nil }
      meta = args[2] || options.fetch(:meta) { nil }
```

Instead, all callers of `Credit.new`, including `Balanced::BankAccount#credit` and `Balanced::Account#credit` should simply pass its options hash to `Credit.new` and have _it_ deal with the option extraction, validation, etc. 

The only differences between `Balanced::BankAccount#credit` and `Balanced::Account#credit` should be in the implementation details of those two methods (which from what I can tell is only `destination_uri`).

I am going to try to fix this and submit a PR shortly... but yea, the ruby code base could use some cleanin' in general :)

**Comment by mahmoudimus** [comment]
@alexnotov has fixed this and I've confirmed it is passed through
