### ISSUE TITLE
Account#hold doesn't accept appears_on_statement_as parameter

### ISSUE THREAD

**Issue by joeyAghion** [balanced/balanced-ruby#40]
[API docs](https://github.com/balanced/balanced-api/blob/master/resources/holds.rst) refer to the `appears_on_statement_as` argument for creating a hold, but the `Account#hold` implementation seems to drop that parameter.

**Comment by mjallday** [comment]
Hey Joey,

This is a bug in the documentation for holds! `appears_on_statement_as` is only used when creating a debit. 

Balanced will attempt to set what appears on the statement to the domain name of your site when creating a hold, however this is poorly supported by Amex and debit cards so it's not something that we expose via the API.

Thanks for bringing this to our attention, I've [created an issue](https://github.com/balanced/balanced-api/issues/161) in the Balanced API repo to track this issue.
