### ISSUE TITLE
Balanced::Marketplace.my_marketplace should memoize the response

### ISSUE THREAD

**Issue by ajsharp** [balanced/balanced-ruby#41]
There are a lot of places in the code that invoke `my_marketplace` in order to acquire what are essentially static values. For example, the `Balanced::Account` does the following in it's initializer in order to get the marketplace's accounts_uri:

``` ruby
module Balanced
  # An Account represents a user within your Marketplace. An Account can have
  # two +roles+. If the Account has the +buyer+ role then you may create
  # Debits using this Account. If they have the +merchant+ role then you may
  # create Credits to transfer funds to this Account.
  #
  class Account
    include Balanced::Resource

    def initialize attributes = {}
      Balanced::Utils.stringify_keys! attributes
      unless attributes.has_key? 'uri'
        attributes['uri'] = Balanced::Marketplace.my_marketplace.send(self.class.collection_name + '_uri')
      end
      super attributes
    end
  end
end
```

Most other resources in the ruby client do this same thing.

This means that every single call to initialize a new `Balanced::Account` object will go over the network to get info about the marketplace, which is essentially static information. Once we have it once for the runtime, I don't think we need to fetch it again. Happy to write a patch for this if we're in agreement about the solution.

**Comment by mjallday** [comment]
+1 We [already do this](https://github.com/balanced/balanced-python/blob/master/balanced/resources.py#L757) in balanced-python.

**Comment by ajsharp** [comment]
Cool, i'll submit a PR in a few.

**Comment by mjallday** [comment]
Note that there needs to be a way to flush the cache, the `Balanced::Marketplace` object has an `in_escrow` field which changes per transaction so people are going to want to be able to see that value.

**Comment by ajsharp** [comment]
Hmm. This sounds like it might be slightly more complicated. What is the `in_escrow` property?

Maybe a more tactical approach would be to fix how the uri's are generated in the initializers. So, instead of invoking `.my_marketplace` every time, all that's needed is the marketplace id, and the url generation can be static, right?

``` ruby
def url_for(resource_name)
  "/v1/#{marketplace_id}/resource"
end

url_for('accounts') # => "/v1/marketplaces/12345/accounts"
```

**Comment by ajsharp** [comment]
I see that there's a `collection_path` method in `lib/balanced/resources/resource.rb`, but that looks like it's going to generate url's in the form of "/v1/accounts". Is the marketplaces/:id portion of the url string optional?

For brevity:

``` ruby
   # lib/balanced/resources/resource.rb:78
    def collection_path
      ["/v#{Balanced.config[:version]}", collection_name].compact.join '/'
    end
```

**Comment by mahmoudimus** [comment]
@ajsharp constructing uris is generally an anti-pattern for REST. The reason you're looking to memoize the my_marketplace is to speed up uri retrieval, right?

**Comment by ajsharp** [comment]
Yep, exactly. Maybe we can cache that which rarely changes, such as the uri fields (accounts_uri, etc), and let the other stuff pass through to network calls. What do you think?
