### ISSUE TITLE
buyer.cards returns single card and a 'todo message'

### ISSUE THREAD

**Issue by harryj** [balanced/balanced-ruby#5]
calling buyer.cards prints:

"TODO: return the pager for this class: Balanced::Card"

and returns a single card. I'm assuming at some point buyer.cards will return an array of cards, not a single card object?

**Comment by harryj** [comment]
So it seems you can access the buyer's card that the buyer was created with via buyer.cards.items.first and then pull fields off that ie buyer.cards.items.first['is_valid']. From the other issue it seems that add_card does not currently work so can't test trying to get multiple cards from buyer.

**Comment by harryj** [comment]
Oops sorry the above syntax is not correct, it should be Balanced::Cards.find(buyer.cards_uri).items.first.  This at least will give you a hash of the properties of the card, not the actual card object itself?

**Comment by mjallday** [comment]
I'm not sure on ruby symantics but in our python library `find` will return a single record, we use `filter` to return multiple results.

e.g.

```
card = Balanced::Cards.find(buyer.card_uri)
```

or 

```
card = Balanced::Cards.filter(buyer.cards_uri).items.first
```

Does this make sense in ruby too?
