### ISSUE TITLE
Balanced::Account.promote_to_merchant ignores user data on PUT

### ISSUE THREAD

**Issue by kalabiyau** [balanced/balanced-ruby#57]
By DOCS - first we create an account with no data

``` ruby
require 'balanced'
Balanced.configure('473154884ae511e28f34026ba7cd33d0')

marketplace = Balanced::Marketplace.my_marketplace

merchant_data =  {
  :phone_number => '+14089999999',
  :name => 'Timmy Q. CopyPasta',
  :dob => '1989-12',
  :postal_code => '94110',
  :type => 'person',
  :street_address => '121 Skriptkid Row',
}

account = Balanced::Marketplace.my_marketplace.create_account

account.promote_to_merchant(merchant_data)
```

Logs on dashboard contain two request POST for creation and PUT for promotion. Anyway - promote - does not respect provided email, name and so on. Getting this resource back does not contain any provided by merchant_data hash results. Is it ok ?
CURL request does this thing in one request(POST) without a problem.

Seems related to API background not the gem, because code looks ok.

**Comment by mjallday** [comment]
Hey @kalabiyau 

From your example it doesn't look like you're passing in the name and email address. 

The promote method only accepts merchant data which is used for underwriting the merchant associated with the account but does not actually update the email address or name on the account itself.

To update those either pass through the email and name when creating the account initially or do it in a separate, subsequent update. Eg

```
account.name = 'blah'
account.email_address = 'user@domain.com'
account.save
```

**Comment by kalabiyau** [comment]
@mjallday thanx !
