### ISSUE TITLE
add_card returns account if card is already associated

### ISSUE THREAD

**Issue by mb-dev** [balanced/balanced-ruby#66]
While testing the library, I added a credit card to the account using:
account.add_card(credit_card_uri)

the 2nd time I got back instance of account instead of card

**Comment by mahmoudimus** [comment]
Thanks for reporting. I'll take a look and fix this ASAP.

**Comment by remear** [comment]
Stale. v1.0 now operates directly on FundingInstruments, so `card.associate_to_customer(customer)`
