### ISSUE TITLE
Re-saving a bank account invalidates it

### ISSUE THREAD

**Issue by mjallday** [balanced/balanced-ruby#71]
This gist shows an example of a [bank account invalidating itself](https://gist.github.com/mjallday/5157581) when save is called a second time.

The issue is the way the balanced-ruby client serializes the account that is returned to the server. Since Balanced cannot parse the account as it is returned it takes this to mean "disassociate this bank account from the account" and invalidates it during this process.

The balanced-ruby library should not set the account in the payload that goes back to Balanced.

**Comment by bb-cyrus** [comment]
I am seeing the same issue with cards. 
I was trying to add a tag in the card's meta to indicate it's a default, but calling save on the card invalidates it.

card.meta["default"] = 1
puts "valid" if card.is_valid
card.save
puts "invalid" if !card.is_valid

**Comment by bninja** [comment]
fixed in [0.7.0](https://github.com/balanced/balanced-ruby/commit/abe4284d9184b11a56f12f7a66d3f377a5e59d98)

**Comment by jrus** [comment]
Hi folks,

It’s only a temporary fix, and not ideal, but it is possible to work around this by creating a new ruby object when updating. For instance, for @bb-cyrus's example above:

```
new_card = Balanced::Card.new(:uri => card.uri, :meta => {"default" => 1}).save
puts "still valid" if new_card.is_valid
```

**Comment by jrus** [comment]
Oh... or just update the client. thanks @bninja!
