### ISSUE TITLE
docs link in README wrong

### ISSUE THREAD

**Issue by jrochkind** [balanced/balanced-ruby#74]
The README says:

> See https://www.balancedpayments.com/docs/overview?language=ruby for tutorials and documentation.

But this does not actually get you to anything involving docs of this gem, no matter how many links you follow. 

Actual docs are at:
https://www.balancedpayments.com/docs/api?language=ruby

or for generated rdocs: http://rubydoc.info/gems/balanced

(thanks Remear on support IRC)

Might be a lot less confusing if you corrected the README to have these links?

**Comment by tanookiben** [comment]
Well the README does mention _tutorials_ and documentation as a description for the link. The overview page provides info on Balanced workflows (and some code snippets), so I wouldn't consider it to not be "tutorials and documentation."

The link to the API is at the top of the page as "API reference," without having to follow any links even.

**Comment by jrochkind** [comment]
Okay, it's your call, it's your project.  It took me a while, and help on the IRC channel, to actually find the docs I needed to get started with the balanced ruby gem.  For me, the overview page was not the docs I needed to actually use the balanced ruby gem, I was lost.  But I may not be typical.

**Comment by mahmoudimus** [comment]
@sicophrenic @jrochkind - we can add it to both. No problems. :)

**Comment by mjallday** [comment]
I just [added both links as well as a link to the examples](https://github.com/balanced/balanced-ruby/commit/3a9c66ae89b21e5ce366ed14b5d80298688103ce). Let us know if this is a good change!
