### ISSUE TITLE
Class misnamed

### ISSUE THREAD

**Issue by mjallday** [balanced/balanced-ruby#77]
There should be a class called `Balanced::BankAccountVerification` however it's called `Balanced::Verification`. 

This is an issue because in the documentation it's called a [BankAccountVerification](https://www.balancedpayments.com/docs/api?language=ruby#retrieve-a-verification-for-a-bank-account)

**Comment by jrus** [comment]
Does the code currently work using 'Verification'? If so, is this maybe a documentation issue rather than a ruby client issue? What do the other client libraries do? Does existing customer code rely on this being called 'Verification'?

**Comment by remear** [comment]
Resolved in v1.0
