### ISSUE TITLE
Customers documentation bugs

### ISSUE THREAD

**Issue by mjallday** [balanced/balanced-ruby#85]
The docstrings for the [`add_card`](https://github.com/balanced/balanced-ruby/blob/master/lib/balanced/resources/customer.rb#L63) and [`add_bank_account`](https://github.com/balanced/balanced-ruby/blob/master/lib/balanced/resources/customer.rb#L74) methods state they return the passed in objects but they return the customer object they are associated with.

**Comment by cyrusstoller** [comment]
+1
