### ISSUE TITLE
Invalid usage of Object.hash in customers.rb

### ISSUE THREAD

**Issue by mahmoudimus** [balanced/balanced-ruby#88]
[`Balanced::Customer.add_bank_account`](https://github.com/balanced/balanced-ruby/blob/master/lib/balanced/resources/customer.rb#L76) has a bug where `.hash` is accessed instead of `fingerprint`.

Also, `.hash` is a reserved method in Ruby, so, the `Balanced::Customer.add_card` is wrong as well.

**Comment by mahmoudimus** [comment]
ping @rloomba

**Comment by remear** [comment]
BankAccount has a fingerprint attribute so that change is simple.

Card has a hash attribute. What do you want to do about that?

**Comment by mahmoudimus** [comment]
@remear brought up that `hash` on the `Balanced::Card` object is fine.
