### ISSUE TITLE
Account#add_card and Account#add_bank_account should accept Card and BankAccount objects as arguments

### ISSUE THREAD

**Issue by Grantismo** [balanced/balanced-ruby#91]
[`Balanced::Account#add_card`](https://github.com/balanced/balanced-ruby/blob/master/lib/balanced/resources/account.rb#L115)
should accept a `Balanced::Card` as an argument.

[`Balanced::Account#add_bank_account`](https://github.com/balanced/balanced-ruby/blob/master/lib/balanced/resources/account.rb#L124)
should accept a `Balanced::BankAccount` as an argument.

**Comment by cyrusstoller** [comment]
+1
