### ISSUE TITLE
change active_card and active_bank_account to match api change

### ISSUE THREAD

**Issue by matthewfl** [balanced/balanced-ruby#99]
The api now supports setting the default card and bank account by PUTing to the source_uri and destination_uri.  Then the default source will be represented by the value of source_uri and destination_uri.

https://github.com/balanced/balanced-ruby/blob/master/lib/balanced/resources/customer.rb#L83

**Comment by remear** [comment]
There is now a bug where default card is being set something other than the newest when source_uri isn't explicitly set.

**Comment by mjallday** [comment]
A good solution here may be to only send data that has been updated on the resource to the server instead of echoing back everything. However, why does the `source_uri` come back if it's not already the default?

**Comment by remear** [comment]
v1.0 now operates around FundingInstruments and not through Customer.
